on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: echo "Juan Pablo Tellez Becerra"
      - run: node --version
      - run: echo "734071"